# -*- coding: utf-8 -*-
"""2DIsing_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yqWbDLDMfNyzJBHvH-PlNRk_4-mYcJh
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numba import njit

"""
2D Ising Model Simulation with Dynamic Temperature and External Field
---------------------------------------------------------------------

This project simulates the 2D Ising Model using the Metropolis–Hastings algorithm.
The system starts at a low temperature with random spin orientations and gradually
heats up. At a specific timestep, an external magnetic field is applied, leading to
partial spin alignment before further thermal disordering.

Outputs:
- Energy, magnetization, and specific heat as functions of temperature
- Spin configuration snapshots during evolution
- Results displayed in a formatted table at the end
"""

# --------------------------
# Initialization
# --------------------------
def initialize_lattice(N):
    """Randomly initializes lattice spins (+1 or -1)."""
    return np.random.choice([1, -1], size=(N, N))

# --------------------------
# Numba-accelerated Metropolis update
# --------------------------
@njit
def metropolis_step(lattice, T, J=1.0, H=0.0):
    """Performs one Metropolis sweep with external field H."""
    N = lattice.shape[0]
    for _ in range(N * N):
        i = np.random.randint(0, N)
        j = np.random.randint(0, N)
        spin = lattice[i, j]

        # ΔE includes nearest-neighbor interactions and external field
        nb_sum = (
            lattice[i, (j + 1) % N] +
            lattice[i, (j - 1) % N] +
            lattice[(i + 1) % N, j] +
            lattice[(i - 1) % N, j]
        )
        delta_E = 2 * J * spin * nb_sum + 2 * H * spin

        if delta_E < 0 or np.random.rand() < np.exp(-delta_E / T):
            lattice[i, j] = -spin
    return lattice

# --------------------------
# Measurements
# --------------------------
def calculate_magnetization(lattice):
    """Compute magnetization per spin."""
    return np.sum(lattice) / lattice.size

def calculate_energy(lattice, J=1.0, H=0.0):
    """Compute total energy per spin."""
    N = lattice.shape[0]
    energy = 0.0
    for i in range(N):
        for j in range(N):
            spin = lattice[i, j]
            energy -= J * spin * (
                lattice[i, (j + 1) % N] + lattice[(i + 1) % N, j]
            )
            energy -= H * spin
    return energy / lattice.size

def calculate_specific_heat(energies, temperatures):
    """Numerically approximate specific heat as dE/dT."""
    dE = np.gradient(energies)
    dT = np.gradient(temperatures)
    return dE / dT

# --------------------------
# Dynamic simulation
# --------------------------
def dynamic_ising(N=400, T_initial=0.7, T_final=5.0, steps=100, J=1.0):
    """
    Simulates Ising model with increasing temperature and applied external field
    at step 30. Returns observables and spin snapshots.
    """
    lattice = initialize_lattice(N)
    magnetizations, energies, temperatures = [], [], []
    snapshots = {}

    for step in range(steps):
        # Linear temperature ramp
        T = T_initial + (T_final - T_initial) * step / steps
        H = 0.0

        # Apply external field after step 30
        if step >= 30:
            H = 0.5

        # Metropolis update
        lattice = metropolis_step(lattice, T, J, H)

        # Measurements
        M = calculate_magnetization(lattice)
        E = calculate_energy(lattice, J, H)

        magnetizations.append(M)
        energies.append(E)
        temperatures.append(T)

        # Store snapshots for visualization
        if step in [0,10,20,30,40,50,60,70,80,90,99]:
            snapshots[step] = lattice.copy()

    # Compute specific heat
    specific_heats = calculate_specific_heat(energies, temperatures)

    # Create DataFrame (no file saving)
    data = pd.DataFrame({
        "Step": np.arange(steps),
        "Temperature": temperatures,
        "Energy": energies,
        "Magnetization": magnetizations,
        "Specific_Heat": specific_heats
    })

    print("\n📊 Simulation Results (first 10 steps):\n")
    print(data.head(10).round(4))  # print only first rows for brevity
    print("\n✅ Simulation completed successfully!\n")

    return data, snapshots

# --------------------------
# Visualization
# --------------------------
def plot_snapshots(snapshots):
    """Visualize spin configurations at selected timesteps."""
    fig, axes = plt.subplots(1, len(snapshots), figsize=(20, 4))
    for ax, (step, lattice) in zip(axes, snapshots.items()):
        ax.imshow(lattice, cmap='bwr', vmin=-1, vmax=1)
        ax.set_title(f"t = {step}")
        ax.axis("off")
    plt.suptitle("Spin Configuration Evolution", fontsize=14)
    plt.show()

def plot_observables(data):
    """Plot energy, specific heat, and magnetization vs temperature."""
    plt.figure(figsize=(8,6))
    plt.plot(data["Temperature"], data["Energy"], 'r-o')
    plt.title("Energy vs Temperature")
    plt.xlabel("Temperature")
    plt.ylabel("Energy per spin")
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(8,6))
    plt.plot(data["Temperature"], data["Specific_Heat"], 'b-o')
    plt.title("Specific Heat vs Temperature")
    plt.xlabel("Temperature")
    plt.ylabel("Specific Heat (a.u.)")
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(8,6))
    plt.plot(data["Temperature"], data["Magnetization"], 'k-o')
    plt.title("Magnetization vs Temperature")
    plt.xlabel("Temperature")
    plt.ylabel("Magnetization per spin")
    plt.grid(True)
    plt.show()

# --------------------------
# Run the Simulation
# --------------------------
if __name__ == "__main__":
    data, snapshots = dynamic_ising(N=400, steps=100)
    plot_snapshots(snapshots)
    plot_observables(data)

