# -*- coding: utf-8 -*-
"""Bose-Einstein Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERSElwnuA5SGewaDkhK64gaGootwLCeH
"""

# ----------------------------
# Bose-Einstein Condensation Simulation
# ----------------------------

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import hbar, k, pi, m_u
from scipy.special import zeta

# ----------------------------
# 1. Constants and parameters for Rubidium-87
# ----------------------------
mass_rb87 = 87 * m_u      # Mass of rubidium-87 atom (kg)
density = 1e18            # Particle density (particles/m^3)
k_B = k                   # Boltzmann constant
omega = 2 * pi * 100      # Trap frequency (Hz, example)
N_total = 1e6             # Total number of particles

# 3D ideal Bose gas critical temperature
T_c_gas = (2 * pi * hbar**2 / k_B / mass_rb87) * (density / zeta(3/2))**(2/3)
print(f"Critical temperature for uniform gas: {T_c_gas:.2e} K")

# Approximate critical temperature in 3D harmonic trap
T_c_trap = (hbar * omega / k_B) * ((N_total / np.pi)**(1/3))
print(f"Critical temperature in harmonic trap: {T_c_trap:.2e} K")

# ----------------------------
# 2. Fraction of particles in ground state
# ----------------------------
temperatures_norm = np.linspace(0.01, 2, 500)  # T/Tc range
ground_state_fraction = np.where(
    temperatures_norm < 1,
    1 - temperatures_norm**(3/2),
    0
)

plt.figure(figsize=(8,6))
plt.plot(temperatures_norm, ground_state_fraction, label="Ground State Fraction", color="magenta")
plt.axvline(1, color="grey", linestyle="--", label="$T = T_c$")
plt.xlabel("Temperature (T / T_c)")
plt.ylabel("Fraction in Ground State ($N_0/N$)")
plt.title("Fraction of Particles in the Ground State")
plt.grid(True)
plt.legend()
plt.show()

# ----------------------------
# 3. Energy spectrum for 3D harmonic oscillator
# ----------------------------
num_levels = 100
energy_levels = hbar * omega * (np.arange(num_levels) + 0.5)

def bose_einstein(energy, T):
    """Average occupation number for each energy level at temperature T."""
    return 1 / (np.exp(energy / (k_B * T)) - 1)

# ----------------------------
# 4. Total Energy & Heat Capacity
# ----------------------------
def calculate_thermodynamic_properties(T):
    populations = bose_einstein(energy_levels, T)
    total_energy = np.sum(populations * energy_levels)

    # Numerical derivative for heat capacity
    dT = 1e-6 * T_c_trap
    total_energy_next = np.sum(bose_einstein(energy_levels, T + dT) * energy_levels)
    heat_capacity = (total_energy_next - total_energy) / dT
    return total_energy, heat_capacity

temperatures = np.linspace(0.1 * T_c_trap, 2 * T_c_trap, 100)
total_energies = []
heat_capacities = []

for T in temperatures:
    E, C = calculate_thermodynamic_properties(T)
    total_energies.append(E)
    heat_capacities.append(C)

# ----------------------------
# 5. Plot Total Energy & Heat Capacity
# ----------------------------
plt.figure(figsize=(14,6))

# Total Energy
plt.subplot(1,2,1)
plt.plot(temperatures/T_c_trap, total_energies, label="Total Energy", color="magenta")
plt.axvline(1, color="grey", linestyle="--", label="$T = T_c$")
plt.xlabel("Temperature (T / T_c)")
plt.ylabel("Total Energy (J)")
plt.title("Total Energy vs Temperature")
plt.grid(True)
plt.legend()

# Heat Capacity
plt.subplot(1,2,2)
plt.plot(temperatures/T_c_trap, heat_capacities, label="Heat Capacity", color="grey")
plt.axvline(1, color="red", linestyle="--", label="$T = T_c$")
plt.xlabel("Temperature (T / T_c)")
plt.ylabel("Heat Capacity (J/K)")
plt.title("Heat Capacity vs Temperature")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

# ----------------------------
# 6. Average population vs energy index at selected temperatures
# ----------------------------
temperatures_for_population = [0.5 * T_c_trap, 0.8 * T_c_trap, T_c_trap, 1.5 * T_c_trap, 2 * T_c_trap]
plt.figure(figsize=(8,6))

for T in temperatures_for_population:
    populations = bose_einstein(energy_levels, T)
    plt.plot(np.arange(num_levels), populations, marker='o', label=f"T = {T/T_c_trap:.1f} T_c")

plt.title("Average Population vs Energy Index")
plt.xlabel("Energy Index (n)")
plt.ylabel("Average Population")
plt.yscale("log")  # Log scale to highlight differences
plt.grid(True)
plt.legend()
plt.show()

